"""The cards at the top of the README, and the page they lead to.

A broken link in a README fails silently and in public: nothing builds, no
test goes red, and the first anybody knows is somebody clicking a title and
landing on nothing. These are cheap to check, so they are checked.

The release page itself is generated by docs/make-releases.py out of the same
table the program reads at run time. What is checked here is that it has been
regenerated since the table last changed, because a stale page is worse than
no page: it says a release is recognised when the program no longer thinks so.
"""

import os
import re
import sys
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from ps3tools import titles                                # noqa: E402

README = os.path.join(ROOT, "README.md")
PAGE = os.path.join(ROOT, "docs", "tested-releases.md")
MAKER = os.path.join(ROOT, "docs", "make-releases.py")
CARDS = os.path.join(ROOT, "docs", "cards")


def read(path):
    with open(path, encoding="utf-8") as handle:
        return handle.read()


def anchor_for(heading):
    """A heading as GitHub turns it into a fragment."""
    text = re.sub(r"[^\w\s-]", "", heading.strip().lower())
    return re.sub(r"\s+", "-", text)


#: The one card that links somewhere other than this repository's own notes.
#: The Modern Warfare 2 fix is built from work published there, so the card
#: leads to the work rather than to this project's page about it.
OUTSIDE_LINK = "https://github.com/jacob-schroeder/IW4-Binaries"


class TheCardsAtTheTop(unittest.TestCase):
    """Eight titles, four across and two down, each one a link."""

    def setUp(self):
        self.readme = read(README)
        self.page = read(PAGE)

    def links(self):
        return re.findall(r'href="docs/tested-releases\.md#([^"]+)"',
                          self.readme)

    def outside_links(self):
        return [url for url in re.findall(r'<a href="(https?://[^"]+)">',
                                          self.readme)
                if url in (OUTSIDE_LINK,)]

    def images(self):
        return re.findall(r'src="(docs/cards/[^"]+)"', self.readme)

    def test_there_are_eight_of_them(self):
        self.assertEqual(len(self.images()), 8)
        self.assertEqual(len(self.links()) + len(self.outside_links()), 8)

    def test_the_modern_warfare_2_card_leads_to_the_work_it_came_from(self):
        self.assertEqual(self.outside_links(), [OUTSIDE_LINK])
        self.assertIn(f'<a href="{OUTSIDE_LINK}"><img '
                      f'src="docs/cards/modern-warfare-2.svg"', self.readme)

    def test_every_card_is_a_link_to_a_heading_that_exists(self):
        headings = {anchor_for(found) for found
                    in re.findall(r"^#+\s+(.*)$", self.page, re.M)}
        for link in self.links():
            self.assertIn(link, headings,
                          f"the {link} card leads nowhere on the page")

    def test_every_card_has_a_picture_that_exists(self):
        for image in self.images():
            self.assertTrue(os.path.isfile(os.path.join(ROOT, image)), image)

    def test_the_pictures_are_our_own_drawings(self):
        # Drawn by docs/make-cards.py from shapes and text. Nothing about
        # these games is ours to publish, so nothing here is a photograph, a
        # logo or a piece of box art, and an SVG of real text is a thing
        # anybody can check by opening it.
        for image in self.images():
            body = read(os.path.join(ROOT, image))
            self.assertIn("<svg", body)
            self.assertNotIn("<image", body)
            self.assertNotIn("data:image", body)
            self.assertIn("<text", body)

    def test_every_card_says_what_it_is_for_a_reader_who_cannot_see_it(self):
        for alt in re.findall(r'<img src="docs/cards/[^"]+" alt="([^"]*)"',
                              self.readme):
            self.assertTrue(alt.strip(), "a card with no alt text")
            self.assertIn(",", alt, f"{alt!r} does not say the status")

    def test_the_three_fixed_titles_are_the_ones_with_a_patcher(self):
        fixed = [image for image in self.images()
                 if "fixed" in self.alt_for(image)]
        self.assertEqual(len(fixed), len(titles.TITLES), fixed)

    def alt_for(self, image):
        found = re.search(re.escape(image) + r'" alt="([^"]*)"', self.readme)
        return found.group(1) if found else ""


class TheCardsAreLegible(unittest.TestCase):
    """A status word nobody can read is a card that says nothing.

    The first drawing of these put "out of scope" in the border colour, which
    is a hairline colour and not a text colour. It came out at 1.41:1 and was
    invisible on screen while looking perfectly reasonable in the source.
    """

    def maker(self):
        import importlib.util
        spec = importlib.util.spec_from_file_location(
            "make_cards", os.path.join(ROOT, "docs", "make-cards.py"))
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module

    def test_every_status_reads_against_the_card_and_the_tile(self):
        module = self.maker()
        for status, token in module.STATUS_TOKENS.items():
            colour = module.DARK[token]
            for ground in ("surface", "bg"):
                ratio = module.contrast_ratio(colour, module.DARK[ground])
                self.assertGreaterEqual(
                    ratio, 4.5,
                    f"{status} on {ground} is only {ratio:.2f}:1")

    def test_the_two_quiet_statuses_are_told_apart_some_other_way(self):
        # They share a colour, so the difference has to be drawn. Untested is
        # something nobody has got to; out of scope is something there is
        # nothing to get to, and the application draws a card it will not act
        # on with a broken edge.
        module = self.maker()
        quiet = [status for status, token in module.STATUS_TOKENS.items()
                 if token == "text_dim"]
        self.assertGreater(len(quiet), 1)
        self.assertTrue(module.DASHED)
        for status in module.DASHED:
            self.assertIn(status, quiet)

    def test_the_cards_on_disk_are_what_the_script_writes_today(self):
        module = self.maker()
        for name, letters, title, status in module.CARDS:
            path = os.path.join(CARDS, name)
            self.assertTrue(os.path.isfile(path), name)
            self.assertEqual(read(path), module.card_svg(letters, title,
                                                         status), name)

    def test_black_ops_is_drawn_as_fixed_like_the_other_two(self):
        module = self.maker()
        status = {title: state for _name, _letters, title, state
                  in module.CARDS}
        for title in ("Black Ops", "Black Ops II", "Modern Warfare 3"):
            self.assertEqual(status[title], "fixed", title)


class ThePageTheCardsLeadTo(unittest.TestCase):
    """Generated, so the thing to check is that it has been regenerated."""

    def maker(self):
        import importlib.util
        spec = importlib.util.spec_from_file_location("make_releases", MAKER)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module

    def test_it_is_what_the_generator_would_write_today(self):
        """A stale page says a release is recognised when it is not.

        Compared against what the generator produces right now rather than
        against what is committed, so that it answers the question it is for
        on a working tree with edits in it. Run docs/make-releases.py if this
        fails.
        """
        self.assertEqual(read(PAGE), self.maker().build())

    def test_every_release_the_program_knows_is_on_the_page(self):
        page = read(PAGE)
        for config in titles.TITLES.values():
            for title_id in config["title_ids"]:
                if title_id in titles.NOT_A_TITLE:
                    continue
                self.assertIn(title_id, page, title_id)

    def test_a_title_id_the_program_refuses_is_not_listed_as_recognised(self):
        page = read(PAGE)
        for title_id in titles.NOT_A_TITLE:
            self.assertNotIn(title_id, page, title_id)

    def test_it_never_claims_more_than_somebody_has_actually_seen(self):
        """Confirmed on hardware means somebody watched it work.

        The page has to keep that apart from "recognised", which is most of
        the list, so the count of confirmed rows has to match the list of
        builds the generator was told about and nothing else.
        """
        module = self.maker()
        wanted = sum(len(builds) for builds in module.CONFIRMED.values())
        self.assertGreaterEqual(wanted, len(titles.TITLES))
        self.assertEqual(read(PAGE).count("| Confirmed on hardware |"), wanted)

    def test_every_confirmed_build_is_a_release_the_program_knows(self):
        # A build confirmed on hardware that the program does not recognise
        # would be a claim about a release it will refuse to touch.
        for key, builds in self.maker().CONFIRMED.items():
            known = titles.TITLES[key]["title_ids"]
            for title_id, _update in builds:
                self.assertIn(title_id, known, title_id)


if __name__ == "__main__":
    unittest.main()
